import { describe, expect, it } from "vitest";

import {
  managedDeviceCategory,
  managedDeviceDisplayName,
} from "../src/managedDevicePresentation";

describe("managed device presentation", () => {
  it("uses a neutral outlet label for an autogenerated outlet name", () => {
    const device = {
      id: "outlet",
      name: "Tuya Outlet Strip",
      manufacturer: "GHome",
      model: "WP12",
    };

    expect(managedDeviceCategory(device)).toBe("Outlet");
    expect(managedDeviceDisplayName(device)).toBe("Outlet");
  });

  it("uses a neutral water-meter label for an autogenerated sensor name", () => {
    const device = {
      id: "water",
      name: "YINMIK Water Sensor",
      manufacturer: "YINMIK",
      model: "Water 7-in-1",
    };

    expect(managedDeviceCategory(device)).toBe("Water Meter");
    expect(managedDeviceDisplayName(device)).toBe("Water Meter");
  });

  it("preserves a user-assigned name", () => {
    const device = {
      id: "water",
      name: "Sump Probes",
      manufacturer: "YINMIK",
      model: "Water 7-in-1",
    };

    expect(managedDeviceDisplayName(device)).toBe("Sump Probes");
  });
});
